[project]
name = "flibberflow"
version = "0.1.0"
description = "MCP Playground"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "fasthx[jinja]>=2.2.1",
    "jinja2>=3.1.5",
    "mcp-agent>=0.0.7",
    "python-multipart>=0.0.20",
    "sse-starlette>=2.2.1",
    "uvicorn>=0.34.0",
]
