[project]
name = "flibberflow"
version = "0.1.0"
description = "MCP Playground"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.15.1",
    "fastapi>=0.115.11",
    "fasthx[jinja]>=2.2.1",
    "jinja2>=3.1.5",
    "mcp>=1.3.0",
    "psycopg2>=2.9.10",
    "python-multipart>=0.0.20",
    "sse-starlette>=2.2.1",
    "transitions>=0.9.2",
    "uvicorn>=0.34.0",
]
