"""add unique constraint on files

Revision ID: 33d6ec3bc7eb
Revises: d74d2e62ee8f
Create Date: 2025-03-21 05:31:27.748530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d6ec3bc7eb'
down_revision: Union[str, None] = 'd74d2e62ee8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_root_files_root_id_path', 'root_files', ['root_id', 'path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_root_files_root_id_path', 'root_files', type_='unique')
    # ### end Alembic commands ###
