"""Initial database

Revision ID: ceb341e35f52
Revises: 
Create Date: 2025-03-12 18:34:23.303307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceb341e35f52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('flow_templates_pkey'))
    )
    op.create_table('scratchpads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scratchpads_pkey'))
    )
    op.create_table('flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('current_state', sa.String(length=100), nullable=True),
    sa.Column('workflow_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['flow_templates.id'], name=op.f('flows_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('flows_pkey'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], name=op.f('sessions_flow_id_fkey')),
    sa.ForeignKeyConstraint(['template_id'], ['flow_templates.id'], name=op.f('sessions_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], name=op.f('messages_parent_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('content_path', sa.String(length=255), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('source_flow_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_flow_id'], ['flows.id'], name=op.f('artifacts_source_flow_id_fkey')),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('artifacts_source_message_id_fkey')),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.id'], name=op.f('artifacts_source_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('messages')
    op.drop_table('sessions')
    op.drop_table('flows')
    op.drop_table('scratchpads')
    op.drop_table('flow_templates')
    # ### end Alembic commands ###
