"""add roots

Revision ID: d74d2e62ee8f
Revises: d9acbec54ca8
Create Date: 2025-03-20 16:23:56.109351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd74d2e62ee8f'
down_revision: Union[str, None] = 'd9acbec54ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roots_pkey')),
    sa.UniqueConstraint('uri', name=op.f('roots_uri_key'))
    )
    op.create_table('root_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('root_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('atime', sa.DateTime(), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['root_id'], ['roots.id'], name=op.f('root_files_root_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('root_files_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('root_files')
    op.drop_table('roots')
    # ### end Alembic commands ###
