"""add workflow cols

Revision ID: d9acbec54ca8
Revises: 2a12b27cd540
Create Date: 2025-03-17 15:54:51.240799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9acbec54ca8'
down_revision: Union[str, None] = '2a12b27cd540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('current_state', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('workflow_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'error')
    op.drop_column('sessions', 'workflow_data')
    op.drop_column('sessions', 'current_state')
    op.drop_column('sessions', 'status')
    # ### end Alembic commands ###
