
session_templates:
  hone_idea:
    description: Hone a business idea, produce high level goal
    metadata:
      tags: ['ideation', 'business']
      owner: wesnick
      version: 0.1
    model: "ollama/gemma3"
    steps:
      - name: System setup
        type: message
        role: system
        content: |
          You are an AI business consultant tasked with helping an entrepreneur refine their business idea
          through an interactive conversation. Your goal is to guide the conversation to determine
          project duration, concrete outcomes, constraints, desired approach, and create a
          detailed specification.

      - name: Create ideation prompt
        type: prompt
        role: user
        template: '@system/hone_idea.md.j2'

      - name: Interactive chat (multiturn)
        type: user_input

      - name: Export Spec
        type: prompt
        content: Extract the spec as a markdown document
        output_schema: ProjectSpecification
