# Scan these modules for pydantic classes for input/output schemas
schema_modules:
  - src.types

template_paths:
  '@system': templates/prompts

#  "APPDATA",
#  "HOMEDRIVE",
#  "HOMEPATH",
#  "LOCALAPPDATA",
#  "PATH",
#  "PROCESSOR_ARCHITECTURE",
#  "SYSTEMDRIVE",
#  "SYSTEMROOT",
#  "TEMP",
#  "USERNAME",
#  "USERPROFILE",
# Can also be added at runtime
mcp_servers:
  repomix:
    command: npx
    args: [-y, repomix, --mcp]
    env: ~

