# Scan these modules for pydantic classes for input/output schemas
schema_modules:
  - src.types

template_paths:
  '@system': templates/prompts

mcp_servers:
  repomix:
    command: /home/wes/.nvm/nvm-exec
    args: [npx, -y, repomix, --mcp]
    env:
      NODE_VERSION: v22.13.1
  filesystem:
    command: /home/wes/.nvm/nvm-exec
    args: [npx, -y, @modelcontextprotocol/server-filesystem, "/home/wes/Downloads"]
    env:
      NODE_VERSION: v22.13.1
