
dialog_templates:
  hone_idea:
    description: Hone a business idea, produce high level goal
    metadata:
      tags: ['ideation', 'business']
      owner: wesnick
      version: 0.1
    model: "ollama_chat/qwq:latest"
    steps:
      - name: System setup
        type: message
        role: system
        content: |
          You are an AI business consultant tasked with helping an entrepreneur refine their business idea
          through an interactive conversation. Your goal is to guide the conversation to determine
          project duration, concrete outcomes, constraints, desired approach, and create a
          detailed specification.

      - name: Create ideation prompt
        type: prompt
        role: user
        template: '@system/hone_idea.md.j2'

      - name: Interactive chat (multiturn)
        type: user_input

      - name: Export Spec
        type: prompt
        template: '@system/extract_spec.md.j2'
        output_schema: ProjectSpecification

  simple_qa:
    description: Simple Question & Answer workflow
    model: "ollama_chat/qwq:latest"
    steps:
      - name: Ask for Topic
        type: user_input
        prompt: "What topic would you like to discuss?"
      - name: Generate Question
        type: prompt
        template: '@system/ask_question.md.j2' # Assumes template exists: "Ask a simple question about {{ user_input }}."
        template_args:
          topic: "{{ user_input }}" # This syntax might need adjustment based on how variables are accessed
      - name: Get Answer
        type: user_input
        prompt: "{{ step_results['Generate Question'].response.text }}" # Display the generated question as prompt
      - name: Conclude
        type: message
        role: system
        content: "Thank you for your answer."

  text_summarizer:
    description: Summarize provided text
    model: "ollama_chat/qwq:latest"
    steps:
      - name: Get Text
        type: user_input
        prompt: "Please paste the text you want to summarize:"
      - name: Summarize Text
        type: prompt
        template: '@system/summarize.md.j2' # Assumes template exists: "Summarize the following text:\n\n{{ user_input }}"
        template_args:
          text_to_summarize: "{{ user_input }}" # Needs variable access check
      - name: Display Summary
        type: message
        role: system
        template: '@system/display_summary.md.j2' # Assumes template: "Here is the summary:\n\n{{ step_results['Summarize Text'].response.text }}"
        template_args:
          summary: "{{ step_results['Summarize Text'].response.text }}" # Needs variable access check

  basic_calculator:
    description: Add two numbers
    model: "ollama_chat/qwq:latest" # Model not really used here, but required
    steps:
      - name: Get First Number
        type: user_input
        prompt: "Enter the first number:"
        output_schema: "number" # Hypothetical schema for validation/coercion
      - name: Get Second Number
        type: user_input
        prompt: "Enter the second number:"
        output_schema: "number" # Hypothetical schema for validation/coercion
      - name: Add Numbers
        type: invoke
        callable: "src.core.workflow.invokables.add_numbers"
        args:
          num1: "{{ step_results['Get First Number'].input }}" # Needs variable access check
          num2: "{{ step_results['Get Second Number'].input }}" # Needs variable access check
      - name: Display Result
        type: message
        role: system
        template: '@system/display_result.md.j2' # Assumes template: "The result is: {{ step_results['Add Numbers'].result }}"
        template_args:
          result: "{{ step_results['Add Numbers'].result }}" # Needs variable access check
