
session_templates:
  hone_idea:
    description: Hone a business idea, produce high level goal
    metadata:
      tags: ['ideation', 'business']
      owner: wesnick
      version: 0.1
    model: "anthropic.claude-3-7-sonnet-20250219-v1:0"     # litellm model

    # Available tools and resources
    tools: []
    resources: []

    # Schema validation (optional)
#    input_schema: string          # Registered schema name for session input
#    output_schema: string         # Registered schema name for session output

    # Execution behavior
#    error_handling: # Default error handling strategy
#      strategy: string            # One of: "fail", "retry", "continue", "fallback"
#      max_retries: integer        # Maximum number of retry attempts
#      fallback_step: string       # Step ID to jump to on failure

    # Execution flow
    steps:
      - name: System setup
        type: message
        role: system
        content: |
          You are an AI business consultant tasked with helping an entrepreneur refine their business idea
          through an interactive conversation. Your goal is to guide the conversation to determine
          project duration, concrete outcomes, constraints, desired approach, and create a
          detailed specification.

      - name: Seed the idea
        type: message
        role: user
        content: I


    # Detailed documentation of available step types
    step_types:
      - message: # Print message with specified role
          fields:
            - role: string          # One of: "system", "user", "assistant"
            - content: string       # Text content of the message

      - prompt: # Generate completion from LLM
          fields:
            - content: string       # Direct content to use as prompt
            - template: string      # Registered template name to use
            - template_args: object # Arguments to pass to the template
            - input_schema: string  # Schema to validate template_args
            - output_schema: string # Schema to validate LLM response
            - config: object        # Step-specific configuration overrides
            - error_handling: object # Step-specific error handling

      - user_input: # Wait for manual input from user
          fields:
            - prompt: string        # Text to display to user when requesting input
            - template: string      # Template to format user input
            - input_schema: string  # Schema to validate user input
            - config: object        # Step-specific configuration
            - output_schema: string # Schema to validate processed input
            - error_handling: object # Step-specific error handling

      - invoke: # Call code function
          fields:
            - callable: string      # Function identifier to call
            - args: object          # Arguments to pass to function
            - input_schema: string  # Schema to validate args
            - output_schema: string # Schema to validate function result
            - error_handling: object # Step-specific error handling


    # Common structure for all step types
    step_structure:
      name: string                 # Concise descriptive name
      description: string          # Detailed purpose of the step
      type: string                 # One of the defined step types
      enabled: boolean             # Whether the step is active (default: true)

      # Step type-specific fields (only relevant fields for the chosen type are used)
      role: string                 # For message steps: user, assistant, system
      content: string              # Text content for message or prompt
      template: string             # Registered template name
      template_args: object        # Args to pass to template
      input_schema: string         # Registered input schema name
      output_schema: string        # Registered output schema name
      callable: string             # Function to call for invoke steps
      args: object                 # Arguments for invoke steps

      # Step-specific metadata
      metadata: object             # Additional information for tracking/debugging

      # Error handling for this step
      error_handling:
        strategy: string           # One of: "fail", "retry", "continue", "fallback"
        max_retries: integer       # Maximum retry attempts
        fallback_step: string      # Step ID to execute on failure

      # Configuration overrides for this step
      config:
        model: string                   # Override default model
        temperature: float              # Override default temperature
        max_tokens: integer             # Override default max tokens
        tools: list[string|object]      # Override or extend available tools
        tool_merge_strategy: string     # One of: "replace", "append", "prepend"
        resources: list[string|object]  # Override or extend available resources
        resource_merge_strategy: string # One of: "replace", "append", "prepend"
